spring.application.name=ObjectStoreDB
data=data
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# Tomcat Configuration for large uploads
server.tomcat.connection-timeout=10m
server.tomcat.keep-alive-timeout=10m


server.tomcat.disable-upload-timeout=false
server.tomcat.connection-upload-timeout=600000


server.tomcat.max-swallow-size=-1
#server.connection-timeout=10m



